'use strict';

const { applySafeWorkflowContracts } = require('./safe-workflow-contracts');

// Explicit inventory: adding or removing a published guide is visible in review.
module.exports = Object.freeze(applySafeWorkflowContracts([
  require('./advanced-timer'),
  require('./animazingpal'),
  require('./api-bridge'),
  require('./chatango'),
  require('./clarityhud'),
  require('./coinbattle'),
  require('./config-import'),
  require('./emoji-rain'),
  require('./fireworks'),
  require('./flame-overlay'),
  require('./game-engine'),
  require('./gcce'),
  require('./gift-catalog'),
  require('./goals'),
  require('./interactive-story'),
  require('./milestone-leaderboard'),
  require('./minecraft-connect'),
  require('./multicam'),
  require('./music-bot'),
  require('./openshock'),
  require('./osc-bridge'),
  require('./quiz-show'),
  require('./schnorrbecher'),
  require('./soundboard'),
  require('./spotlight'),
  require('./stream-monsters'),
  require('./stt-ticker'),
  require('./talking-heads'),
  require('./thermal-printer'),
  require('./toptier'),
  require('./tts'),
  require('./vdoninja'),
  require('./visual-fx-frame-webgpu'),
  require('./weather-control'),
  require('./webgpu-weather-control'),
  require('./webgpu-emoji-rain'),
  require('./webgpu-fireworks'),
  require('./store-admin'),
]));
