'use strict';

const fs = require('fs');
const path = require('path');

const DEFAULT_REPO_ROOT = path.resolve(__dirname, '..');
const DEFAULT_OUTPUT_PATH = path.join(
  DEFAULT_REPO_ROOT,
  'js',
  'streammonsters-catalog.generated.js'
);
const LOCALES = Object.freeze(['de', 'en', 'es', 'fr']);
const CHOICES = Object.freeze(['A', 'B', 'C']);

function readRulesVersion(repoRoot) {
  const rulesPath = path.join(
    repoRoot,
    'app',
    'plugins',
    'streamalchemy',
    'backend',
    'streammonsters',
    'battle-rules-v8.js'
  );
  const rulesVersion = Number(require(rulesPath).RULES_VERSION);
  if (!Number.isInteger(rulesVersion) || rulesVersion < 1) {
    throw new Error('STREAM_MONSTERS_PUBLIC_RULES_VERSION_INVALID');
  }
  return rulesVersion;
}

function readMonsterLocales(repoRoot) {
  return Object.fromEntries(LOCALES.map(locale => {
    const localePath = path.join(
      repoRoot,
      'app',
      'plugins',
      'streamalchemy',
      'locales',
      `${locale}.json`
    );
    const document = JSON.parse(fs.readFileSync(localePath, 'utf8'));
    const monsters = document?.plugins?.streamalchemy?.ui?.monsters;
    if (!monsters || typeof monsters !== 'object') {
      throw new Error(`STREAM_MONSTERS_PUBLIC_LOCALE_MISSING:${locale}`);
    }
    return [locale, monsters];
  }));
}

function requiredTranslation(localeDocuments, locale, key) {
  const value = localeDocuments[locale]?.[key];
  if (typeof value !== 'string' || !value.trim()) {
    throw new Error(
      `STREAM_MONSTERS_PUBLIC_TRANSLATION_MISSING:${locale}:${key}`
    );
  }
  return value;
}

function publicAssetPath(template, stage) {
  if (stage === 1) {
    return `/assets/streammonsters/furry/${template.templateId}.webp`;
  }
  return (
    `/assets/streammonsters/furry/evolution/${template.element.toLowerCase()}/` +
    `${template.templateId}-stage${stage}.webp`
  );
}

function publicSkill(runtimeSkill, localeDocuments) {
  const skill = {
    choice: runtimeSkill.choice,
    id: runtimeSkill.id,
    type: runtimeSkill.type,
    icon: runtimeSkill.icon,
    nameKey: runtimeSkill.nameKey,
    effectKey: runtimeSkill.effectKey,
    effects: runtimeSkill.effects.map(effect => ({ ...effect })),
    translations: Object.fromEntries(LOCALES.map(locale => [
      locale,
      {
        name: requiredTranslation(
          localeDocuments,
          locale,
          runtimeSkill.nameKey
        ),
        effect: requiredTranslation(
          localeDocuments,
          locale,
          runtimeSkill.effectKey
        )
      }
    ]))
  };
  if (Number.isFinite(runtimeSkill.chargeRequired)) {
    skill.chargeRequired = runtimeSkill.chargeRequired;
  }
  return skill;
}

function buildPublicCatalog({ repoRoot = DEFAULT_REPO_ROOT } = {}) {
  const resolvedRepoRoot = path.resolve(repoRoot);
  const runtimeCatalogPath = path.join(
    resolvedRepoRoot,
    'app',
    'plugins',
    'streamalchemy',
    'backend',
    'streammonsters',
    'catalog.js'
  );
  const runtimeCatalog = require(runtimeCatalogPath);
  const rulesVersion = readRulesVersion(resolvedRepoRoot);
  const localeDocuments = readMonsterLocales(resolvedRepoRoot);
  const templates = runtimeCatalog.TEMPLATE_CATALOG.map(template => ({
    templateId: template.templateId,
    element: template.element,
    role: template.role,
    name: runtimeCatalog.projectDefaultMonsterName(
      template.templateId,
      template.name
    ),
    species: template.species,
    epithet: template.epithet,
    season: template.season,
    stages: [1, 2, 3].map(stage => ({
      stage,
      assetPath: publicAssetPath(template, stage),
      skills: CHOICES.map(choice => publicSkill(
        runtimeCatalog.resolveStageSkill(
            template.templateId,
            choice,
            stage,
            rulesVersion
        ),
        localeDocuments
      ))
    }))
  }));

  return {
    schemaVersion: 1,
    rulesVersion,
    locales: [...LOCALES],
    templateCount: templates.length,
    formCount: templates.reduce(
      (total, template) => total + template.stages.length,
      0
    ),
    skillCount: templates.reduce(
      (total, template) => total + template.stages.reduce(
        (stageTotal, stage) => stageTotal + stage.skills.length,
        0
      ),
      0
    ),
    templates
  };
}

function renderBrowserCatalog(publicCatalog) {
  return (
    '// Generated by scripts/build_streammonsters_public_catalog.js. Do not edit.\n' +
    '(function attachStreamMonstersPublicCatalog(root) {\n' +
    "  'use strict';\n" +
    `  root.STREAM_MONSTERS_PUBLIC_CATALOG = ${JSON.stringify(
      publicCatalog,
      null,
      2
    )};\n` +
    '})(typeof window !== \'undefined\' ? window : globalThis);\n'
  );
}

function normalizeLineEndings(source) {
  return String(source || '').replace(/\r\n?/g, '\n');
}

function parseArguments(argv) {
  const options = {
    check: false,
    outputPath: DEFAULT_OUTPUT_PATH,
    repoRoot: DEFAULT_REPO_ROOT
  };
  for (let index = 0; index < argv.length; index += 1) {
    const argument = argv[index];
    if (argument === '--check') {
      options.check = true;
    } else if (argument === '--output') {
      options.outputPath = path.resolve(argv[index + 1]);
      index += 1;
    } else if (argument === '--repo-root') {
      options.repoRoot = path.resolve(argv[index + 1]);
      index += 1;
    } else {
      throw new Error(`STREAM_MONSTERS_PUBLIC_ARGUMENT_UNKNOWN:${argument}`);
    }
  }
  return options;
}

function main(argv = process.argv.slice(2)) {
  const options = parseArguments(argv);
  const publicCatalog = buildPublicCatalog({ repoRoot: options.repoRoot });
  const generatedSource = renderBrowserCatalog(publicCatalog);

  if (options.check) {
    const currentSource = fs.existsSync(options.outputPath)
      ? fs.readFileSync(options.outputPath, 'utf8')
      : '';
    if (
      normalizeLineEndings(currentSource) !==
      normalizeLineEndings(generatedSource)
    ) {
      process.stderr.write(
        `Stream Monsters public catalog is stale: ${options.outputPath}\n`
      );
      process.exitCode = 1;
      return false;
    }
    process.stdout.write(
      `Stream Monsters public catalog is current: ` +
      `${publicCatalog.templateCount} templates, ` +
      `${publicCatalog.formCount} forms, ` +
      `${publicCatalog.skillCount} skills.\n`
    );
    return true;
  }

  fs.mkdirSync(path.dirname(options.outputPath), { recursive: true });
  fs.writeFileSync(options.outputPath, generatedSource, 'utf8');
  process.stdout.write(
    `Built ${options.outputPath}: ` +
    `${publicCatalog.templateCount} templates, ` +
    `${publicCatalog.formCount} forms, ` +
    `${publicCatalog.skillCount} skills.\n`
  );
  return true;
}

if (require.main === module) {
  main();
}

module.exports = {
  CHOICES,
  LOCALES,
  buildPublicCatalog,
  main,
  normalizeLineEndings,
  publicAssetPath,
  readRulesVersion,
  renderBrowserCatalog
};
