'use strict';

module.exports = {
  pageCopy: {
    de: {
      title: 'Alle Apps ansehen - ltth.app',
      description:
        'Alle Apps und Features mit Screenshots, Nutzen und Deep-Dive-Links.',
      eyebrow: 'Katalog',
      heading: 'Alle Apps auf einen Blick',
      intro: 'Entdecke die Apps und Features mit echten Screenshots, Nutzen und passenden Deep-Dive-Links.',
      searchLabel: 'Suche',
      searchPlaceholder: 'Katalog durchsuchen',
      tocLabel: 'Kategorien',
      jumpLabel: 'Mobil springen zu',
      resultsLabel: 'Treffer',
      catalogReadyLabel: 'Katalog bereit',
      heroAppsLabel: 'im Katalog',
      heroAppsValue: 'Alle Apps',
      heroScreenshotsLabel: 'Screenshots pro Eintrag',
      heroLanguagesLabel: 'Sprachen',
      clearSearch: 'Suche zurücksetzen',
      deepDiveLabel: 'Deep Dive',
      entryBenefitLabel: 'Nutzen',
      entryContextLabel: 'Einsatzkontext',
      screenshotsLabel: 'Screenshots',
      ctaDownload: 'Jetzt herunterladen',
      ctaDocs: 'Dokumentation',
      ctaHome: 'Zur Startseite',
      ctaApps: 'Alle Apps ansehen',
      noResults: 'Keine Treffer',
      itemListName: 'App-Katalog von ltth.app',
      itemListDescription: 'Alle Apps und Features von ltth.app mit Screenshots, Beschreibungen und Deep-Dive-Links.',
    },
    en: {
      title: 'View all apps - ltth.app',
      description:
        'All apps and features with screenshots, benefits, and deep-dive links.',
      eyebrow: 'Catalog',
      heading: 'All apps at a glance',
      intro: 'Explore the apps and features with real screenshots, benefits, and deep-dive links.',
      searchLabel: 'Search',
      searchPlaceholder: 'Search the catalog',
      tocLabel: 'Categories',
      jumpLabel: 'Jump on mobile',
      resultsLabel: 'results',
      catalogReadyLabel: 'Catalog ready',
      heroAppsLabel: 'in the catalog',
      heroAppsValue: 'All apps',
      heroScreenshotsLabel: 'Screenshots per entry',
      heroLanguagesLabel: 'Languages',
      clearSearch: 'Clear search',
      deepDiveLabel: 'Deep dive',
      entryBenefitLabel: 'Benefit',
      entryContextLabel: 'Use context',
      screenshotsLabel: 'Screenshots',
      ctaDownload: 'Download now',
      ctaDocs: 'Documentation',
      ctaHome: 'Back to home',
      ctaApps: 'View all apps',
      noResults: 'No results found',
      itemListName: 'ltth.app feature catalog',
      itemListDescription:
        'All ltth.app features and apps with screenshots, descriptions, and deep-dive links.',
    },
    es: {
      title: 'Ver todas las apps - ltth.app',
      description:
        'Las apps y funciones con capturas, beneficios y enlaces a los deep dives.',
      eyebrow: 'Catálogo',
      heading: 'Todas las apps de un vistazo',
      intro: 'Explora las apps y funciones con capturas reales, beneficios y enlaces a los deep dives.',
      searchLabel: 'Buscar',
      searchPlaceholder: 'Buscar en el catálogo',
      tocLabel: 'Categorías',
      jumpLabel: 'Ir en móvil',
      resultsLabel: 'resultados',
      catalogReadyLabel: 'Catálogo listo',
      heroAppsLabel: 'en el catálogo',
      heroAppsValue: 'Todas las apps',
      heroScreenshotsLabel: 'Capturas por entrada',
      heroLanguagesLabel: 'Idiomas',
      clearSearch: 'Borrar búsqueda',
      deepDiveLabel: 'Deep dive',
      entryBenefitLabel: 'Beneficio',
      entryContextLabel: 'Contexto de uso',
      screenshotsLabel: 'Capturas',
      ctaDownload: 'Descargar ahora',
      ctaDocs: 'Documentación',
      ctaHome: 'Volver al inicio',
      ctaApps: 'Ver todas las apps',
      noResults: 'No se encontraron resultados',
      itemListName: 'Catálogo de apps de ltth.app',
      itemListDescription: 'Las funciones y apps de ltth.app con capturas, descripciones y enlaces a los deep dives.',
    },
    fr: {
      title: 'Voir toutes les apps - ltth.app',
      description:
        'Les apps et fonctionnalités avec captures, bénéfices et liens vers les deep dives.',
      eyebrow: 'Catalogue',
      heading: 'Toutes les apps en un coup d’oeil',
      intro: 'Explorez les apps et fonctionnalités avec de vraies captures, les bénéfices et des liens vers les deep dives.',
      searchLabel: 'Rechercher',
      searchPlaceholder: 'Rechercher dans le catalogue',
      tocLabel: 'Catégories',
      jumpLabel: 'Accès mobile',
      resultsLabel: 'résultats',
      catalogReadyLabel: 'Catalogue prêt',
      heroAppsLabel: 'dans le catalogue',
      heroAppsValue: 'Toutes les apps',
      heroScreenshotsLabel: 'Captures par entrée',
      heroLanguagesLabel: 'Langues',
      clearSearch: 'Effacer la recherche',
      deepDiveLabel: 'Deep dive',
      entryBenefitLabel: 'Bénéfice',
      entryContextLabel: "Contexte d'usage",
      screenshotsLabel: 'Captures',
      ctaDownload: 'Télécharger maintenant',
      ctaDocs: 'Documentation',
      ctaHome: "Retour à l'accueil",
      ctaApps: 'Voir toutes les apps',
      noResults: 'Aucun résultat',
      itemListName: 'Catalogue de fonctionnalités ltth.app',
      itemListDescription: 'Les fonctionnalités et apps de ltth.app avec captures, descriptions et liens vers les deep dives.',
    },
  },
  categories: [
    {
      id: 'ai',
      label: {
        de: 'KI & Intelligenz',
        en: 'AI & Intelligence',
        es: 'IA e inteligencia',
        fr: 'IA et intelligence',
      },
      intro: {
        de: 'KI-gestützte Assistenten, Avatar-Logik und adaptive Story-Flows für Streams mit mehr Reaktionstiefe.',
        en: 'AI-powered assistants, avatar logic, and adaptive story flows for streams with more reactive depth.',
        es: 'Asistentes impulsados por IA, lógica de avatar y flujos de historias adaptativos para streams con más profundidad reactiva.',
        fr: "Assistants alimentés par l'IA, logique d'avatar et flux d'histoire adaptatifs pour des streams plus réactifs.",
      },
      benefit: {
        de: 'Macht Reaktionen, Personas und narrative Abläufe direkt steuerbar.',
        en: 'Makes reactions, personas, and narrative flows directly controllable.',
        es: 'Hace que las reacciones, las personas y los flujos narrativos sean controlables directamente.',
        fr: 'Rend les réactions, les personas et les flux narratifs directement contrôlables.',
      },
      context: {
        de: 'Für VTuber, Stream-Assistenten und interaktive Live-Erlebnisse.',
        en: 'For VTubers, stream assistants, and interactive live experiences.',
        es: 'Para VTubers, asistentes de stream y experiencias en vivo interactivas.',
        fr: 'Pour les VTubers, assistants de stream et expériences live interactives.',
      },
    },
    {
      id: 'audio',
      label: {
        de: 'Audio & Stimme',
        en: 'Audio & Voice',
        es: 'Audio y voz',
        fr: 'Audio et voix',
      },
      intro: {
        de: 'Sprach- und Soundfunktionen, die Eingaben in hörbare, sofort nutzbare Stream-Momente verwandeln.',
        en: 'Speech and sound features that turn input into audible, immediately usable stream moments.',
        es: 'Funciones de voz y sonido que convierten las entradas en momentos de stream audibles y utilizables al instante.',
        fr: 'Des fonctions de voix et de son qui transforment les entrées en moments de stream immédiatement utilisables.',
      },
      benefit: {
        de: 'Bringt Sprache, Stimme und Sound ohne Umwege in den Live-Flow.',
        en: 'Brings speech, voice, and sound straight into the live flow.',
        es: 'Lleva voz, habla y sonido directamente al flujo en vivo.',
        fr: 'Amène la voix, la parole et le son directement dans le flux live.',
      },
      context: {
        de: 'Für TTS, Soundboard, Untertitel und musikgesteuerte Interaktion.',
        en: 'For TTS, soundboard, captions, and music-driven interaction.',
        es: 'Para TTS, soundboard, subtítulos e interacción impulsada por música.',
        fr: 'Pour le TTS, le soundboard, les sous-titres et l’interaction pilotée par la musique.',
      },
    },
    {
      id: 'visual',
      label: {
        de: 'Visuell & Overlay',
        en: 'Visual & Overlay',
        es: 'Visual y overlay',
        fr: 'Visuel et overlay',
      },
      intro: {
        de: 'Overlays, Effekte und Statusanzeigen, die den Stream sichtbar strukturieren.',
        en: 'Overlays, effects, and status indicators that structure the stream visually.',
        es: 'Overlays, efectos e indicadores de estado que estructuran visualmente el stream.',
        fr: 'Des overlays, effets et indicateurs d’état qui structurent visuellement le stream.',
      },
      benefit: {
        de: 'Macht Events, Ziele und Status direkt im Bild verständlich.',
        en: 'Makes events, goals, and status understandable right in the frame.',
        es: 'Hace comprensibles eventos, objetivos y estado directamente en la imagen.',
        fr: 'Rend les événements, objectifs et statuts compréhensibles directement à l’écran.',
      },
      context: {
        de: 'Für OBS, HUDs, Animationen und sichtbare Reaktionen auf Zuschaueraktionen.',
        en: 'For OBS, HUDs, animations, and visible responses to viewer actions.',
        es: 'Para OBS, HUDs, animaciones y respuestas visibles a las acciones de la audiencia.',
        fr: "Pour OBS, les HUDs, les animations et les réponses visibles aux actions des spectateurs.",
      },
    },
    {
      id: 'games',
      label: {
        de: 'Gaming & Interaktion',
        en: 'Gaming & Interaction',
        es: 'Juegos e interacción',
        fr: 'Jeux et interaction',
      },
      intro: {
        de: 'Spielbare Formate, bei denen Chat, Gifts und Regeln direkt in Unterhaltung umgewandelt werden.',
        en: 'Playable formats that turn chat, gifts, and rules directly into entertainment.',
        es: 'Formatos jugables que convierten chat, regalos y reglas directamente en entretenimiento.',
        fr: 'Des formats jouables qui transforment directement le chat, les cadeaux et les règles en divertissement.',
      },
      benefit: {
        de: 'Macht Zuschaueraktionen zu spielbaren Momenten mit klaren Regeln.',
        en: 'Turns audience actions into playable moments with clear rules.',
        es: 'Convierte las acciones de la audiencia en momentos jugables con reglas claras.',
        fr: 'Transforme les actions du public en moments jouables avec des règles claires.',
      },
      context: {
        de: 'Für Quiz, Slots, Game-Engines und interaktive Challenges.',
        en: 'For quizzes, slots, game engines, and interactive challenges.',
        es: 'Para concursos, tragamonedas, motores de juego y desafíos interactivos.',
        fr: 'Pour les quiz, machines à sous, moteurs de jeu et défis interactifs.',
      },
    },
    {
      id: 'system',
      label: {
        de: 'System & Erweiterung',
        en: 'System & Extensions',
        es: 'Sistema y extensiones',
        fr: 'Système et extensions',
      },
      intro: {
        de: 'Werkzeuge für Betrieb, Automation, Updates und die Architektur hinter dem Stream-Setup.',
        en: 'Tools for operations, automation, updates, and the architecture behind the stream setup.',
        es: 'Herramientas para operaciones, automatización, actualizaciones y la arquitectura detrás de la configuración del stream.',
        fr: 'Des outils pour l’exploitation, l’automatisation, les mises à jour et l’architecture derrière le setup de stream.',
      },
      benefit: {
        de: 'Hält dein Setup wartbar, erweiterbar und ohne Reibung am Laufen.',
        en: 'Keeps your setup maintainable, extensible, and running without friction.',
        es: 'Mantiene tu configuración mantenible, extensible y en funcionamiento sin fricciones.',
        fr: 'Garde votre configuration maintenable, extensible et fluide au quotidien.',
      },
      context: {
        de: 'Für Plugin-Verwaltung, Event-Routing, Updates und Safety-Schichten.',
        en: 'For plugin management, event routing, updates, and safety layers.',
        es: 'Para gestión de plugins, enrutado de eventos, actualizaciones y capas de seguridad.',
        fr: "Pour la gestion des plugins, le routage d’événements, les mises à jour et les couches de sécurité.",
      },
    },
    {
      id: 'connections',
      label: {
        de: 'Verbindungen & Integrationen',
        en: 'Connections & Integrations',
        es: 'Conexiones e integraciones',
        fr: 'Connexions et intégrations',
      },
      intro: {
        de: 'Integrationen, die LTTH mit externen Plattformen, Geräten und Protokollen verbinden.',
        en: 'Integrations that connect LTTH with external platforms, devices, and protocols.',
        es: 'Integraciones que conectan LTTH con plataformas, dispositivos y protocolos externos.',
        fr: 'Des intégrations qui relient LTTH à des plateformes, appareils et protocoles externes.',
      },
      benefit: {
        de: 'Erweitert den Stream um echte Verbindungen nach außen.',
        en: 'Extends the stream with real connections to the outside world.',
        es: 'Amplía el stream con conexiones reales hacia el exterior.',
        fr: 'Étend le stream avec de vraies connexions vers l’extérieur.',
      },
      context: {
        de: 'Für VRChat, VDO.Ninja, TikFinity, Hardware und Spezial-Workflows.',
        en: 'For VRChat, VDO.Ninja, TikFinity, hardware, and special workflows.',
        es: 'Para VRChat, VDO.Ninja, TikFinity, hardware y flujos de trabajo especiales.',
        fr: 'Pour VRChat, VDO.Ninja, TikFinity, le matériel et les workflows spéciaux.',
      },
    },
  ],
  itemCategoryBySlug: {
    alerts: 'visual',
    animazingpal: 'ai',
    'api-bridge': 'system',
    'auto-updater': 'system',
    'chat-commands': 'system',
    dashboard: 'system',
    'emoji-rain': 'visual',
    'flame-overlay': 'visual',
    'flow-engine': 'system',
    'game-engine': 'games',
    goals: 'visual',
    'interactive-story': 'ai',
    multicam: 'connections',
    'osc-bridge': 'connections',
    overlays: 'visual',
    'plugin-advanced-timer': 'system',
    'plugin-chatango': 'connections',
    'plugin-clarity-hud': 'visual',
    'plugin-config-import': 'system',
    'plugin-data-source': 'system',
    'plugin-gcce': 'system',
    'plugin-gcce-hud': 'visual',
    'plugin-gift-milestone': 'visual',
    'plugin-lastevent-spotlight': 'visual',
    'plugin-leaderboard': 'visual',
    'plugin-minecraft-connect': 'connections',
    'plugin-music-bot': 'audio',
    'plugin-openshock': 'connections',
    'plugin-quiz-show': 'games',
    'plugin-stream-alchemy': 'system',
    'plugin-system': 'system',
    'plugin-thermal-printer': 'connections',
    'plugin-vulkan-rockets': 'visual',
    'plugin-weather-overlay': 'visual',
    security: 'system',
    sidekick: 'ai',
    'slot-machine': 'games',
    soundboard: 'audio',
    'stt-ticker': 'audio',
    'talking-heads': 'ai',
    'tikfinity-api': 'connections',
    toptier: 'visual',
    tts: 'audio',
    vdoninja: 'connections',
    'viewer-xp': 'visual',
  },
  storeIdBySlug: {
    animazingpal: 'animazingpal',
    'api-bridge': 'api-bridge',
    'emoji-rain': 'webgpu-emoji-rain',
    'flame-overlay': 'flame-overlay',
    'game-engine': 'game-engine',
    goals: 'goals',
    'interactive-story': 'interactive-story',
    multicam: 'multicam',
    'osc-bridge': 'osc-bridge',
    'plugin-advanced-timer': 'advanced-timer',
    'plugin-chatango': 'chatango',
    'plugin-clarity-hud': 'clarityhud',
    'plugin-config-import': 'config-import',
    'plugin-data-source': 'data-source',
    'plugin-gcce': 'gcce',
    'plugin-gift-milestone': 'gift-milestone',
    'plugin-lastevent-spotlight': 'spotlight',
    'plugin-leaderboard': 'milestone-leaderboard',
    'plugin-music-bot': 'music-bot',
    'plugin-openshock': 'openshock',
    'plugin-quiz-show': 'quiz-show',
    'plugin-stream-alchemy': 'streamalchemy',
    'plugin-thermal-printer': 'thermal-printer',
    'plugin-vulkan-rockets': 'fireworks',
    'plugin-weather-overlay': 'weather-control',
    sidekick: 'sidekick',
    soundboard: 'soundboard',
    'stt-ticker': 'stt-ticker',
    'talking-heads': 'talking-heads',
    toptier: 'toptier',
    tts: 'tts',
    vdoninja: 'vdoninja',
  },
  manualSummaries: {
    alerts: {
      en: 'Fully customizable alerts for gifts, follows, shares, likes, and subscriptions with sound, text, and image/GIF combinations.',
      es: 'Alertas totalmente personalizables para regalos, follows, compartidos, likes y suscripciones con combinaciones de sonido, texto e imagen/GIF.',
      fr: "Alertes entièrement personnalisables pour les cadeaux, follows, partages, likes et abonnements avec combinaisons son, texte et image/GIF.",
    },
    'auto-updater': {
      en: 'Automatic update checks, one-click patching, version management, rollback support, and update notifications for LTTH.',
      es: 'Comprobación automática de actualizaciones, aplicación de parches con un clic, gestión de versiones, soporte de rollback y notificaciones de actualización para LTTH.',
      fr: 'Vérification automatique des mises à jour, application des correctifs en un clic, gestion des versions, prise en charge du rollback et notifications de mise à jour pour LTTH.',
    },
    'chat-commands': {
      en: 'Define your own !commands for TikTok LIVE, trigger flows, manage cooldowns, and set permission levels.',
      es: 'Define tus propios comandos ! para TikTok LIVE, activa flujos, gestiona tiempos de espera y define niveles de permisos.',
      fr: "Définissez vos propres commandes ! pour TikTok LIVE, déclenchez des flows, gérez les cooldowns et définissez les niveaux d'autorisation.",
    },
    dashboard: {
      en: 'Central control hub with live viewer stats, chat feed, event log, quick actions, and OBS integration.',
      es: 'Centro de control central con estadísticas en vivo de espectadores, feed de chat, registro de eventos, acciones rápidas e integración con OBS.',
      fr: "Centre de contrôle central avec statistiques en direct des spectateurs, flux de chat, journal d'événements, actions rapides et intégration OBS.",
    },
    'flow-engine': {
      en: 'Visual flow editor with event triggers, conditions, loops, and an extensive action library for complex TikTok LIVE automations.',
      es: 'Editor visual de flujos con disparadores de eventos, condiciones, bucles y una amplia biblioteca de acciones para automatizaciones complejas de TikTok LIVE.',
      fr: "Éditeur de flux visuel avec déclencheurs d'événements, conditions, boucles et une vaste bibliothèque d'actions pour des automatisations TikTok LIVE complexes.",
    },
    overlays: {
      en: 'OBS overlays for WebGPU Emoji Rain, Fireworks, Flame Overlay, Weather Engine, Goals HUD, Talking Heads, and the Alert System for TikTok LIVE streamers.',
      es: 'Overlays para OBS: WebGPU Emoji Rain, Fireworks, Flame Overlay, Weather Engine, Goals HUD, Talking Heads y el sistema de alertas para streamers de TikTok LIVE.',
      fr: 'Overlays OBS pour WebGPU Emoji Rain, Fireworks, Flame Overlay, Weather Engine, Goals HUD, Talking Heads et le système d’alertes pour les streamers TikTok LIVE.',
    },
    'plugin-gcce-hud': {
      en: 'HUD overlay for the GCCE command engine. Shows active commands, cooldowns, and permission status in the OBS stream.',
      es: 'Overlay HUD para el motor de comandos GCCE. Muestra comandos activos, tiempos de espera y estado de permisos en la transmisión de OBS.',
      fr: 'Overlay HUD pour le moteur de commandes GCCE. Affiche les commandes actives, les temps de recharge et l’état des permissions dans le stream OBS.',
    },
    'plugin-minecraft-connect': {
      en: 'Minecraft Connect links TikTok events to in-game actions so gifts, chat, and other triggers can reach your world.',
      es: 'Minecraft Connect vincula los eventos de TikTok con acciones dentro del juego para que regalos, chat y otros disparadores lleguen a tu mundo.',
      fr: 'Minecraft Connect relie les événements TikTok aux actions en jeu pour que les cadeaux, le chat et d’autres déclencheurs atteignent votre monde.',
    },
    'plugin-system': {
      en: '30+ built-in plugins, hot reload without restarting, a JavaScript API for custom plugins, and seamless admin UI integration.',
      es: 'Más de 30 plugins integrados, recarga en caliente sin reiniciar, API de JavaScript para plugins propios e integración fluida con la interfaz de administración.',
      fr: '30+ plugins intégrés, rechargement à chaud sans redémarrage, API JavaScript pour vos propres plugins et intégration fluide à l’interface d’administration.',
    },
    security: {
      en: 'CORS configuration, CSP, input validators, rate limiting, and 100% local processing without any cloud dependency for LTTH.',
      es: 'Configuración de CORS, CSP, validadores de entrada, limitación de tasa y procesamiento 100% local sin dependencia de la nube para LTTH.',
      fr: 'Configuration CORS, CSP, validateurs d’entrée, limitation de débit et traitement 100 % local sans dépendance au cloud pour LTTH.',
    },
    'slot-machine': {
      en: 'A 3-reel engine with multi-machine support, custom sound uploads, superfan detection, and a fully customizable design for TikTok LIVE.',
      es: 'Motor de 3 carretes con soporte para varias máquinas, subida de sonidos personalizados, detección de superfans y diseño totalmente personalizable para TikTok LIVE.',
      fr: 'Moteur à 3 rouleaux avec prise en charge de plusieurs machines, import de sons personnalisés, détection des superfans et design entièrement personnalisable pour TikTok LIVE.',
    },
    'tikfinity-api': {
      en: 'Advanced event handling via TikFinity, bidirectional data flow, webhook support, and real-time sync for TikTok LIVE streams.',
      es: 'Gestión avanzada de eventos a través de TikFinity, flujo de datos bidireccional, compatibilidad con webhooks y sincronización en tiempo real para transmisiones de TikTok LIVE.',
      fr: 'Gestion avancée des événements via TikFinity, flux de données bidirectionnel, prise en charge des webhooks et synchronisation en temps réel pour les streams TikTok LIVE.',
    },
    'viewer-xp': {
      en: 'Per-viewer XP tracking, a level system with overlays, leaderboards, and OBS overlay integration for TikTok LIVE.',
      es: 'Seguimiento de XP por espectador, sistema de niveles con overlays, clasificaciones e integración de overlay OBS para TikTok LIVE.',
      fr: 'Suivi XP par spectateur, système de niveaux avec overlays, classements et intégration d’overlay OBS pour TikTok LIVE.',
    },
  },
};
